name: CI/CD Pós-deploy.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Gradle
        run: ./gradlew clean build --no-daemon

      - name: Run Selenium Tests
        run: ./gradlew test --no-daemon
