name: DAST Scan
on:
  pull_request:
    branches: [main, test]
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Subir a aplicação (staging)
        run: |
          ./gradlew bootRun &
          sleep 20 # aguardar app subir

      - name: Instalar OWASP ZAP
        run: |
          sudo apt update
          sudo apt install -y zaproxy

      - name: Executar scan DAST
        run: |
          zap.sh -daemon -port 8090 -host 127.0.0.1 -newsession session1
          zap-cli -p 8090 status -t 120
          zap-cli -p 8090 spider http://localhost:8080
          zap-cli -p 8090 active-scan http://localhost:8080
          zap-cli -p 8090 report -o zap_report.html -f html

      - name: Upload do relatório
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: zap_report.html
